/**
 * Usage Example: JAHysteresisSchedulerLUT
 *
 * This example shows how to use the LUT-optimized JA hysteresis scheduler
 * with the precomputed lookup tables generated by scripts/generate_ja_lut.py
 *
 * CPU reduction: ~11% → ~1% compared to the original scheduler
 */

#include "JAHysteresisSchedulerLUT.h"

// Include the LUT header for your desired mode
// All headers are in faust/JAHysteresisLUT_*.h
// Available: K28, K45, K63, K99, K121, K187, K253, K495, K1045, K2101
#include "../faust/JAHysteresisLUT_K121.h"

class TapeProcessor
{
public:
    void prepareToPlay(double sampleRate)
    {
        // Initialize with default physics
        JAHysteresisSchedulerLUT::PhysicsParams physics;
        physics.Ms = 320.0;
        physics.aDensity = 720.0;
        physics.kPinning = 280.0;
        physics.cReversibility = 0.18;
        physics.alphaCoupling = 0.015;

        scheduler.initialise(sampleRate, JAHysteresisSchedulerLUT::Mode::K121, physics);

        // Set the LUT data pointers for K121 mode
        // The .data() method gets raw pointer from std::array
        scheduler.setLUT(
            JAHysteresisLUT_K121::LUT_M_END.data(),
            JAHysteresisLUT_K121::LUT_SUM_M_REST.data(),
            JAHysteresisLUT_K121::M_SIZE,
            JAHysteresisLUT_K121::H_SIZE
        );

        // Note: LUTs are precomputed for bias_level=0.41, bias_scale=11.0
        // These values are fixed and changing them will cause incorrect results
    }

    void processBlock(float* buffer, int numSamples)
    {
        for (int i = 0; i < numSamples; ++i)
        {
            // Drive signal into JA hysteresis range
            double input = static_cast<double>(buffer[i]) * driveGain;

            // Process through LUT-optimized hysteresis
            double output = scheduler.process(input);

            // Apply output gain
            buffer[i] = static_cast<float>(output * outputGain);
        }
    }

    void setDrive(float driveDb)
    {
        driveGain = std::pow(10.0, driveDb / 20.0);
    }

    void setOutputGain(float gainDb)
    {
        outputGain = std::pow(10.0, gainDb / 20.0);
    }

    // Example: Switching modes at runtime
    // Each mode requires its own LUT to be loaded!
    void setMode(JAHysteresisSchedulerLUT::Mode mode)
    {
        scheduler.setMode(mode);

        // Must set matching LUT data after mode change
        switch (mode)
        {
            case JAHysteresisSchedulerLUT::Mode::K121:
                scheduler.setLUT(
                    JAHysteresisLUT_K121::LUT_M_END.data(),
                    JAHysteresisLUT_K121::LUT_SUM_M_REST.data(),
                    JAHysteresisLUT_K121::M_SIZE,
                    JAHysteresisLUT_K121::H_SIZE
                );
                break;

            // Add cases for other modes as needed...
            // case JAHysteresisSchedulerLUT::Mode::K63:
            //     #include "../faust/JAHysteresisLUT_K63.h"
            //     scheduler.setLUT(...);
            //     break;

            default:
                // Fallback to K121
                scheduler.setLUT(
                    JAHysteresisLUT_K121::LUT_M_END.data(),
                    JAHysteresisLUT_K121::LUT_SUM_M_REST.data(),
                    JAHysteresisLUT_K121::M_SIZE,
                    JAHysteresisLUT_K121::H_SIZE
                );
                break;
        }
    }

private:
    JAHysteresisSchedulerLUT scheduler;
    double driveGain = 1.0;
    double outputGain = 1.0;
};

/**
 * Multi-mode example with all LUTs preloaded
 * Use this pattern if you need to switch modes frequently
 */

// Include all LUT headers
#include "../faust/JAHysteresisLUT_K28.h"
#include "../faust/JAHysteresisLUT_K45.h"
#include "../faust/JAHysteresisLUT_K63.h"
#include "../faust/JAHysteresisLUT_K99.h"
// K121 already included above
#include "../faust/JAHysteresisLUT_K187.h"
#include "../faust/JAHysteresisLUT_K253.h"
#include "../faust/JAHysteresisLUT_K495.h"
#include "../faust/JAHysteresisLUT_K1045.h"
#include "../faust/JAHysteresisLUT_K2101.h"

class MultiModeTapeProcessor
{
public:
    void prepareToPlay(double sampleRate)
    {
        JAHysteresisSchedulerLUT::PhysicsParams physics;
        scheduler.initialise(sampleRate, JAHysteresisSchedulerLUT::Mode::K121, physics);
        setMode(JAHysteresisSchedulerLUT::Mode::K121);
    }

    void setMode(JAHysteresisSchedulerLUT::Mode mode)
    {
        scheduler.setMode(mode);

        // Set matching LUT
        switch (mode)
        {
            case JAHysteresisSchedulerLUT::Mode::K28:
                scheduler.setLUT(JAHysteresisLUT_K28::LUT_M_END.data(),
                                 JAHysteresisLUT_K28::LUT_SUM_M_REST.data(),
                                 JAHysteresisLUT_K28::M_SIZE,
                                 JAHysteresisLUT_K28::H_SIZE);
                break;
            case JAHysteresisSchedulerLUT::Mode::K45:
                scheduler.setLUT(JAHysteresisLUT_K45::LUT_M_END.data(),
                                 JAHysteresisLUT_K45::LUT_SUM_M_REST.data(),
                                 JAHysteresisLUT_K45::M_SIZE,
                                 JAHysteresisLUT_K45::H_SIZE);
                break;
            case JAHysteresisSchedulerLUT::Mode::K63:
                scheduler.setLUT(JAHysteresisLUT_K63::LUT_M_END.data(),
                                 JAHysteresisLUT_K63::LUT_SUM_M_REST.data(),
                                 JAHysteresisLUT_K63::M_SIZE,
                                 JAHysteresisLUT_K63::H_SIZE);
                break;
            case JAHysteresisSchedulerLUT::Mode::K99:
                scheduler.setLUT(JAHysteresisLUT_K99::LUT_M_END.data(),
                                 JAHysteresisLUT_K99::LUT_SUM_M_REST.data(),
                                 JAHysteresisLUT_K99::M_SIZE,
                                 JAHysteresisLUT_K99::H_SIZE);
                break;
            case JAHysteresisSchedulerLUT::Mode::K121:
                scheduler.setLUT(JAHysteresisLUT_K121::LUT_M_END.data(),
                                 JAHysteresisLUT_K121::LUT_SUM_M_REST.data(),
                                 JAHysteresisLUT_K121::M_SIZE,
                                 JAHysteresisLUT_K121::H_SIZE);
                break;
            case JAHysteresisSchedulerLUT::Mode::K187:
                scheduler.setLUT(JAHysteresisLUT_K187::LUT_M_END.data(),
                                 JAHysteresisLUT_K187::LUT_SUM_M_REST.data(),
                                 JAHysteresisLUT_K187::M_SIZE,
                                 JAHysteresisLUT_K187::H_SIZE);
                break;
            case JAHysteresisSchedulerLUT::Mode::K253:
                scheduler.setLUT(JAHysteresisLUT_K253::LUT_M_END.data(),
                                 JAHysteresisLUT_K253::LUT_SUM_M_REST.data(),
                                 JAHysteresisLUT_K253::M_SIZE,
                                 JAHysteresisLUT_K253::H_SIZE);
                break;
            case JAHysteresisSchedulerLUT::Mode::K495:
                scheduler.setLUT(JAHysteresisLUT_K495::LUT_M_END.data(),
                                 JAHysteresisLUT_K495::LUT_SUM_M_REST.data(),
                                 JAHysteresisLUT_K495::M_SIZE,
                                 JAHysteresisLUT_K495::H_SIZE);
                break;
            case JAHysteresisSchedulerLUT::Mode::K1045:
                scheduler.setLUT(JAHysteresisLUT_K1045::LUT_M_END.data(),
                                 JAHysteresisLUT_K1045::LUT_SUM_M_REST.data(),
                                 JAHysteresisLUT_K1045::M_SIZE,
                                 JAHysteresisLUT_K1045::H_SIZE);
                break;
            case JAHysteresisSchedulerLUT::Mode::K2101:
                scheduler.setLUT(JAHysteresisLUT_K2101::LUT_M_END.data(),
                                 JAHysteresisLUT_K2101::LUT_SUM_M_REST.data(),
                                 JAHysteresisLUT_K2101::M_SIZE,
                                 JAHysteresisLUT_K2101::H_SIZE);
                break;
        }
    }

    double process(double input) { return scheduler.process(input); }

private:
    JAHysteresisSchedulerLUT scheduler;
};
